trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndDeploy
  displayName: "Build, Test, and Deploy"
  jobs:
  - job: BuildJob
    displayName: "Build and Test the Application"
    steps:
    - task: Checkout@2
      inputs:
        repository: 'https://github.com/MyDevOpsBlog4u/python_flask_app.git'
        ref: 'refs/heads/main'
        clean: true
      displayName: 'Checkout code from GitHub'
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: "Install Dependencies"

    - script: |
        pytest tests/
      displayName: "Run Unit Tests"

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        includeRootFolder: false
      displayName: "Package Application"

    - task: AzureRmWebAppDeployment@4
      inputs:
        azureSubscription: 'YourAzureServiceConnection'
        appType: 'webAppLinux'
        WebAppName: 'MyFlaskApp3'
        packageForLinux: '$(Build.ArtifactStagingDirectory)/*.zip'
      displayName: "Deploy to Azure App Service"
